<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2026 Johannes Kepler University Linz

  This program and the accompanying materials are made available under the
  terms of the Eclipse Public License 2.0 which is available at
  http://www.eclipse.org/legal/epl-2.0.

  SPDX-License-Identifier: EPL-2.0

  Contributors:
    Alois Zoitl - initial API and implementation and/or initial documentation
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:include schemaLocation="block-common.xsd"/>
<xs:include schemaLocation="fbnetwork.xsd"/>

<xs:complexType name="SubAppInterfaceList">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element name="SubAppEventInputs"  type="SubAppEventInputs"/>
    <xs:element name="SubAppEventOutputs" type="SubAppEventOutputs"/>
    <xs:element name="InputVars"          type="InputVars"/>
    <xs:element name="OutputVars"         type="OutputVars"/>
    <xs:element name="InOutVars"          type="InOutVars"/>
    <xs:element name="Sockets"            type="Sockets"/>
    <xs:element name="Plugs"              type="Plugs"/>
  </xs:choice>
</xs:complexType>

<xs:complexType name="SubAppEventInputs">
  <xs:sequence>
    <xs:element name="SubAppEvent" type="SubAppEvent" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="SubAppEventOutputs">
  <xs:sequence>
    <xs:element name="SubAppEvent" type="SubAppEvent" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="SubAppEvent" mixed="true">
  <xs:sequence>
    <xs:group ref="AttributeGroup"/>
  </xs:sequence>
  <xs:attributeGroup ref="NameTypeCommentAttributes"/>
</xs:complexType>

<xs:complexType name="SubAppNetwork">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:group ref="CommonFBNetworkElements"/>
    <xs:element name="SubApp"             type="SubApp"/>
    <xs:element name="EventConnections"   type="EventConnections"/>
    <xs:element name="DataConnections"    type="DataConnections"/>
    <xs:element name="AdapterConnections" type="AdapterConnections"/>
  </xs:choice>
</xs:complexType>


<xs:complexType name="SubApp">
  <xs:annotation>
    <xs:documentation>
      Constraint: Type and the children SubAppInterfaceList and SubAppNetwork are mutaly exclusive.
    </xs:documentation>
  </xs:annotation>
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element name="SubAppInterfaceList" type="SubAppInterfaceList"/>
    <xs:element name="SubAppNetwork"       type="SubAppNetwork"/>
    <xs:element name="Parameter"           type="Parameter"/>
    <xs:group ref="AttributeGroup"/>
  </xs:choice>
  <xs:attributeGroup ref="NameCommentAttributes"/>
  <xs:attributeGroup ref="PositionAttributes"/>
  <xs:attribute name="Type" type="xs:string" use="optional"/>
</xs:complexType>

</xs:schema>